# Release: https://github.com/scrtlabs/secret-trading-agent-app/releases/tag/v0.0.2
# Workflow URL: https://github.com/scrtlabs/secret-trading-agent-app/actions/runs/15711151187
# Commit: https://github.com/scrtlabs/secret-trading-agent-app/commit/daf5dc07650dbb80b3f685de340ef5159032aa49
version: '3'
services:
  app:
    image: ghcr.io/scrtlabs/secret-trading-agent-app@sha256:73d5c7665e266f33e093977a059c21786499d7779ca9870a5ba13aeb06d17d8c
    ports:
      - '3000:80'
